# Static libzstd from vendor/zstd. Produces target `libzstd_static`.
set(ZSTD_BUILD_STATIC   ON  CACHE BOOL "" FORCE)
set(ZSTD_BUILD_SHARED   OFF CACHE BOOL "" FORCE)
set(ZSTD_BUILD_PROGRAMS OFF CACHE BOOL "" FORCE)
set(ZSTD_BUILD_TESTS    OFF CACHE BOOL "" FORCE)
set(ZSTD_BUILD_CONTRIB  OFF CACHE BOOL "" FORCE)
set(ZSTD_LEGACY_SUPPORT OFF CACHE BOOL "" FORCE)

add_subdirectory(
    ${CMAKE_SOURCE_DIR}/vendor/zstd/build/cmake
    ${CMAKE_BINARY_DIR}/zstd
    EXCLUDE_FROM_ALL
)

set(BFC_NODE_ZSTD_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/vendor/zstd/lib CACHE INTERNAL "")
